import type { Metadata } from "next";
import { Fraunces, Plus_Jakarta_Sans, Geist_Mono, Outfit, Ovo } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";

// const fraunces = Fraunces({
 
//   subsets: ["latin"],
//   variable: "--font-fraunches"
// });

// const geistMono = Geist_Mono({
 
//   subsets: ["latin"],
//   variable:"--font-geist-mono"
// });


// const plusJakartaSans = Plus_Jakarta_Sans({
  
//   subsets: ["latin"],
//   variable:"--font-body"
// });

const outfit = Outfit({

  subsets:["latin"],
  variable:"--font-outfit"

});

const ovo = Ovo({
  subsets: ["latin"],
  variable: "--font-ovo",
  weight: "400"
})
export const metadata: Metadata = {
  title: "Mousumi's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" className="scroll-smooth" 
    >
      <body className={`min-h-full  flex flex-col ${outfit.className} ${ovo.className} h-full antialiased leading-8 overflow-x-hidden`}>
        <Header/>
        {children}
        </body>
    </html>
  );
}
